server:
  port: 8040
spring:
   application:
     name: SERVICE-STREAM
 cloud: 
    config: 
      discovery: 
        enabled: true
        serviceId: SERVICE-CONFIG
      profile: DEV     
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:1112/eureka/
   instance:
     preferIpAddress: false