server:
  port: 8219
spring:
   application:
     name: service-sr
 cloud: 
    config: 
      discovery: 
        enabled: true
        serviceId: SERVICE-CONFIG
      profile: DEV     
     
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:1112/eureka/
   instance:
     preferIpAddress: false
     
     
     
zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
     baseUrl: http://localhost:9411/
sleuth:
    sampler:
      percentage: 1.0

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: true
     
##     
logging:
  config: classpath:log4j2-dev.xml