spring: 
  application: 
    name: service-gateway
 cloud: 
    config: 
      discovery: 
        enabled: true
        serviceId: SERVICE-CONFIG
      profile: DEV

server:
  port: 4000
      
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://127.0.0.1:1112/eureka/
    instance:
     preferIpAddress: false
zuul:
  # ignored-services: microservice-provider-user # 需要忽视的服务(配置后将不会被路由)
   routes:
      user: # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
        path: /sr/** # 想要映射到的路径
        service-id: service-sr # Eureka中的serviceId   
                
# Logger config
logging:
  config: classpath:log4j2-dev.xml