spring: 
  application: 
    name: service-gateway
  cloud: 
    config: 
      discovery: 
        enabled: true
        serviceId: service-config
      profile: prod

server: 
  port: 3111
      
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://registry1.hxd:1111/eureka/,http://registry2.hxd:1111/eureka/
  instance: 
    prefer-ip-address: true #注册时使用ip地址
    
# Logger config
logging:
  config: classpath:log4j2-prod.xml
