server:
  port: 8218
spring:
   application:
     name: SERVICE-DEALER
 cloud: 
    config: 
      discovery: 
        enabled: true
        serviceId: SERVICE-CONFIG
      profile: DEV
     
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:1111/eureka/
   instance:
     preferIpAddress: false