spring: 
  application: 
    name: job-service
  cloud: 
    config: 
      discovery: 
        enabled: true
        serviceId: SERVICE-CONFIG
      profile: DEV

server: 
  port: 11111
      
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:1112/eureka/
  instance: 
    prefer-ip-address: true #注册时使用ip地址

# Logger config
logging:
  config: classpath:log4j2-dev.xml
