spring: 
  application: 
    name: sms-service
 cloud: 
    config: 
      discovery: 
        enabled: true
        serviceId: SERVICE-CONFIG
      profile: DEV

server: 
  port: 7768
      
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://127.0.0.1:1112/eureka/
  instance: 
    prefer-ip-address: true #注册时使用ip地址
    
# Logger config
logging:
  config: classpath:log4j2-dev.xml